assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS03AXPS-PC03A-05-ADCPTD302
stream:
  method: streamed
  name: adcp_engineering
workflow_config:
  schedule: 0 0 * * *
